<?php
//21 AGO 07

define("PREGUNTAS_POR_PAGINA",20);
define("VERSION_DEMO",false);

//define("DEBUG_HABILITAR_",false);

define("USUARIO_APLICADOR_EXTA",7);
define("USUARIO_DIRECTOR",6);

define("USUARIO_ADMINISTRADOR",5);
define("USUARIO_VISITANTE",3);
define("USUARIO_SUPERVISOR",2);
define("USUARIO_APLICADOR",1);
define("USUARIO_ALUMNOS",0);

?>